"""added requests of products

Revision ID: 1c5e3cd32c02
Revises: eab9bb7a2db4
Create Date: 2022-05-22 07:34:07.430506

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c5e3cd32c02'
down_revision = 'eab9bb7a2db4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
