"""refacor

Revision ID: 2c360c5f9f71
Revises: a8f17afe1912
Create Date: 2022-05-24 10:20:52.462299

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c360c5f9f71'
down_revision = 'a8f17afe1912'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('request', schema=None) as batch_op:
        batch_op.drop_column('amount_payable')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('request', schema=None) as batch_op:
        batch_op.add_column(sa.Column('amount_payable', sa.FLOAT(), nullable=True))

    # ### end Alembic commands ###
