"""Init

Revision ID: b8b4aac88bd6
Revises: 848f384fa6d6
Create Date: 2022-05-20 09:19:55.689073

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8b4aac88bd6'
down_revision = '848f384fa6d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
